// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHLvPgnh_H0bi248dfQpZPwvbeAbFlF24',
    appId: '1:640793220118:web:b030183534c5e9a0f55137',
    messagingSenderId: '640793220118',
    projectId: 'notesapp-6a8c5',
    authDomain: 'notesapp-6a8c5.firebaseapp.com',
    storageBucket: 'notesapp-6a8c5.firebasestorage.app',
    measurementId: 'G-X6EVRXP4S2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6iMMdZPjRQ8mPaUa9BCgPoHDWP2z7ESs',
    appId: '1:640793220118:android:5b69ab64366792f9f55137',
    messagingSenderId: '640793220118',
    projectId: 'notesapp-6a8c5',
    storageBucket: 'notesapp-6a8c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOO3SAXglWvV1KWdnGCa3-nJrcBihSrvU',
    appId: '1:640793220118:ios:e53d7a98dfdb067bf55137',
    messagingSenderId: '640793220118',
    projectId: 'notesapp-6a8c5',
    storageBucket: 'notesapp-6a8c5.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOO3SAXglWvV1KWdnGCa3-nJrcBihSrvU',
    appId: '1:640793220118:ios:e53d7a98dfdb067bf55137',
    messagingSenderId: '640793220118',
    projectId: 'notesapp-6a8c5',
    storageBucket: 'notesapp-6a8c5.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHLvPgnh_H0bi248dfQpZPwvbeAbFlF24',
    appId: '1:640793220118:web:35cf5d0cca95f770f55137',
    messagingSenderId: '640793220118',
    projectId: 'notesapp-6a8c5',
    authDomain: 'notesapp-6a8c5.firebaseapp.com',
    storageBucket: 'notesapp-6a8c5.firebasestorage.app',
    measurementId: 'G-55YY06X78L',
  );
}
